### ISSUE TITLE
[BUG] Runtime Error: "Config validation error: "SECRET_KEY" is required. "JWT_SECRET" is required."

### ISSUE THREAD

**Issue by stackdev19** [vencake/resume#1]
Runtime error: 
`Config validation error: "SECRET_KEY" is required. "JWT_SECRET" is required.`

**Comment by rjholo** [comment]
Did you rename file `.env.example` into `.env`? Make sure that `SECRET_KEY`, `JWT_SECRET` are configured in it.

**Comment by rjhollo** [comment]
It is already done. It seems not to be configured from `.env` file

**Comment by rjholo** [comment]
How did you run it?

**Comment by rjhollo** [comment]
`yarn dev:server`

**Comment by rjholo** [comment]
I will check soon.

**Comment by rjholo** [comment]
Hi, @stackdev19 .
You should use `yarn dev` insetead of `yarn dev:server`. `yarn dev:server` tried to find `.env` file in 'server' workspace.
Can you resolve it?

**Comment by stackdev19** [comment]
Yes, I close the issue.
